[project]
name = 'Inventory-Management-and-Demand-Forecasting-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.demand-forecasting]
path = 'contracts/demand-forecasting.clar'
clarity_version = 2
epoch = 2.5

[contracts.location-management]
path = 'contracts/location-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
